In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data_job = pd.read_csv('alldata_new.csv')

In [3]:
data_job.head()

position             company  \
0                               Development Director             ALS TDI   
1  An Ostentatiously-Excitable Principal Research...  The Hexagon Lavish   
2                                     Data Scientist      Xpert Staffing   
3                                       Data Analyst      Operation HOPE   
4  Assistant Professor -TT - Signal Processing & ...    Emory University   

   reviews     City State      Zip  
0      NaN  Atlanta   GA   30301.0  
1      NaN  Atlanta    GA      NaN  
2      NaN  Atlanta    GA      NaN  
3     44.0  Atlanta   GA   30303.0  
4    550.0  Atlanta    GA      NaN

In [4]:
data_job.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6964 entries, 0 to 6963
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   position  6953 non-null   object 
 1   company   6953 non-null   object 
 2   reviews   5326 non-null   float64
 3   City      6953 non-null   object 
 4   State     6953 non-null   object 
 5   Zip       2143 non-null   float64
dtypes: float64(2), object(4)
memory usage: 326.6+ KB


In [5]:
data_job.shape

(6964, 6)

In [6]:
data_job.dtypes

position     object
company      object
reviews     float64
City         object
State        object
Zip         float64
dtype: object

## Checking for duplicates

In [7]:
data_dup = data_job[data_job.duplicated(keep="last")]
data_dup.shape

(10, 6)

There are 10 duplicate rows

In [8]:
# Drop duplicate rows
data_job = data_job.drop_duplicates()
data_job.shape

(6954, 6)

In [9]:
data_job.head()

position             company  \
0                               Development Director             ALS TDI   
1  An Ostentatiously-Excitable Principal Research...  The Hexagon Lavish   
2                                     Data Scientist      Xpert Staffing   
3                                       Data Analyst      Operation HOPE   
4  Assistant Professor -TT - Signal Processing & ...    Emory University   

   reviews     City State      Zip  
0      NaN  Atlanta   GA   30301.0  
1      NaN  Atlanta    GA      NaN  
2      NaN  Atlanta    GA      NaN  
3     44.0  Atlanta   GA   30303.0  
4    550.0  Atlanta    GA      NaN

## Check for missing values

### Replace continuous null values with the mode

In [10]:
data_job['reviews'].isnull().sum()

1628

There are 1628 missing values in review column

In [11]:
mode_review = data_job['reviews'].mode()[0]

data_job['reviews'] = data_job['reviews'].fillna(mode_review)

In [12]:
data_job['reviews'].isnull().sum()

0

In [13]:
data_job['Zip'].isnull().sum()

4811

There are 4811 missing values in zip column

In [14]:
mode_zip = data_job['Zip'].mode()[0]
data_job['Zip'] = data_job['Zip'].fillna(mode_zip)

In [15]:
data_job['Zip'].isnull().sum()

0

### Replace categorical columns null values with unknowns

In [16]:
data_job['position'] = data_job['position'].fillna('unknown')
data_job['company'] = data_job['company'].fillna('unknown')
data_job['City'] = data_job['City'].fillna('unknown')
data_job['State'] = data_job['State'].fillna('unknown')

In [17]:
data_job.head()

position             company  \
0                               Development Director             ALS TDI   
1  An Ostentatiously-Excitable Principal Research...  The Hexagon Lavish   
2                                     Data Scientist      Xpert Staffing   
3                                       Data Analyst      Operation HOPE   
4  Assistant Professor -TT - Signal Processing & ...    Emory University   

   reviews     City State      Zip  
0  25902.0  Atlanta   GA   30301.0  
1  25902.0  Atlanta    GA  98052.0  
2  25902.0  Atlanta    GA  98052.0  
3     44.0  Atlanta   GA   30303.0  
4    550.0  Atlanta    GA  98052.0

In [18]:
data_job.isnull().sum()

position    0
company     0
reviews     0
City        0
State       0
Zip         0
dtype: int64

In [21]:
clean_data = data_job

In [23]:
clean_data.shape

(6954, 6)

In [22]:
clean_data.to_csv('clean_data.csv', index=False)